apiVersion: v1
kind: Namespace
metadata:
  name: default
spec:
  finalizers:
    - kubernetes

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logixprofedev
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logixprofedev
  template:
    metadata:
      labels:
        app: logixprofedev
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: logixprofedev
          image: plmmodernization.azurecr.io/LogixProFE-dev:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: '0'
              memory: '0'
            limits:
              cpu: '1'
              memory: 1G

---

apiVersion: v1
kind: Service
metadata:
  name: plmkub-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: http
      port: 80
      protocol: TCP
    - targetPort: 443
      name: https
      port: 443
      protocol: TCP
  selector:
    app: logixprofedev
